project:
  type: website
  output-dir: docs

website:
  title: "Pierre Smith - CV"
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Projets"
        href: projets.qmd

  page-footer:
    right: "Dernière mise à jour : 08/10/2025"
format:
  html:
    theme: cosmo
